//! Port of `com.unifocus.watson.server.hibernate.entity.PlannedShift`.
//!
//! Ground truth not re-read in full for this wave — field slice matches `DATA_MODEL.md` §3 plus
//! `process/plannedshiftsorters/PlannedShiftSorter.java`. `assignment_order_no` flattens
//! `getAssignment().getAssignmentOrder().getOrderNo()` — the only thing that sort reads off the
//! shift's assignment chain — rather than carrying nested `Assignment`/`AssignmentOrder` types,
//! same treatment as `EmployeeJobStatus.job_parent_assignment_id` (see `entity` module docs).
//!
//! `job_id` was added for `PlannedShiftLoader` (Phase 2 step 1), the first caller of `getJob()` —
//! flattened to the id rather than a nested `Assignment`, same treatment as `assignment_order_no`.
//!
//! `assignment_id`/`end_date_time`/`shift_category_id` were added for `PlannedShiftCreator`
//! (Phase 2 step 6), its first writer — `with_*` builder fields defaulting to `None`/
//! `start_date_time`, following `entity::employee_shift::EmployeeShift`'s pattern, since not
//! every existing constructor call site sets them. `assignment_id` is the raw FK
//! `setAssignment(Assignment)` writes — a genuinely different field from the already-existing
//! `assignment_order_no` (a value *derived from* the assignment chain for the sorters, not the
//! assignment reference itself). `shift_type`/`source`/`date_shift_generated_from` are not
//! modeled — `PlannedShiftCreator` sets each to a fixed constant on every path, and nothing reads
//! any of them back yet, so they're inert until a reader appears.

use date_range_rs::DateTimeRange;
use joda_rs::{LocalDate, LocalDateTime};

/// A shift generated by the planner, to be filled by the scheduling engine. `PlannedShift`.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct PlannedShift {
    id: i32,
    job_id: i32,
    shift_date: LocalDate,
    start_date_time: LocalDateTime,
    end_date_time: LocalDateTime,
    duration: f64,
    assignment_order_no: Option<i32>,
    assignment_id: Option<i32>,
    shift_category_id: Option<i32>,
}

impl PlannedShift {
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        id: i32,
        job_id: i32,
        shift_date: LocalDate,
        start_date_time: LocalDateTime,
        duration: f64,
        assignment_order_no: Option<i32>,
    ) -> Self {
        Self {
            id,
            job_id,
            shift_date,
            start_date_time,
            end_date_time: start_date_time,
            duration,
            assignment_order_no,
            assignment_id: None,
            shift_category_id: None,
        }
    }

    /// `setEndDateTime(LocalDateTime)`.
    #[must_use]
    pub fn with_end_date_time(mut self, end_date_time: LocalDateTime) -> Self {
        self.end_date_time = end_date_time;
        self
    }

    /// `setAssignment(Assignment)`.
    #[must_use]
    pub fn with_assignment_id(mut self, assignment_id: Option<i32>) -> Self {
        self.assignment_id = assignment_id;
        self
    }

    /// `setShiftCategory(ShiftCategory)`.
    #[must_use]
    pub fn with_shift_category_id(mut self, shift_category_id: Option<i32>) -> Self {
        self.shift_category_id = shift_category_id;
        self
    }

    /// `getID()`.
    pub fn id(&self) -> i32 {
        self.id
    }

    /// `getJob().getID()`.
    pub fn job_id(&self) -> i32 {
        self.job_id
    }

    /// `getShiftDate()`.
    pub fn shift_date(&self) -> LocalDate {
        self.shift_date
    }

    /// `getStartDateTime()`.
    pub fn start_date_time(&self) -> LocalDateTime {
        self.start_date_time
    }

    /// `getDuration()`.
    pub fn duration(&self) -> f64 {
        self.duration
    }

    /// `getAssignment().getAssignmentOrder().getOrderNo()` — `null` when the shift has no
    /// assignment, or the assignment has no `AssignmentOrder`.
    pub fn assignment_order_no(&self) -> Option<i32> {
        self.assignment_order_no
    }

    /// `getEndDateTime()`.
    pub fn end_date_time(&self) -> LocalDateTime {
        self.end_date_time
    }

    /// `getAssignment().getID()` — `null` when the shift has no assignment.
    pub fn assignment_id(&self) -> Option<i32> {
        self.assignment_id
    }

    /// `getShiftCategory().getID()` — `null` when the shift has no category.
    pub fn shift_category_id(&self) -> Option<i32> {
        self.shift_category_id
    }

    /// `toDateTimeRange()`.
    pub fn to_date_time_range(&self) -> DateTimeRange {
        DateTimeRange::of(self.start_date_time, self.end_date_time)
    }
}
