//! Port of `com.unifocus.watson.server.hibernate.entity.PreSchedule`.
//!
//! Ground truth: `taps/src/java/com/unifocus/watson/server/hibernate/entity/PreSchedule.java`.
//! `getComment()`/`getScheduleDate()` aren't modeled — nothing `PreScheduleProcess` (Phase 2 step
//! 6, this type's only ported reader so far) does reads either; `PreScheduleDAO`'s query filters
//! on `scheduleDate` itself, but that's abstracted away entirely behind
//! `engine::io::ports::PreScheduleDAOPort`. `employee`/`job`/`assignment`/`shiftCategory` flatten
//! to ids, same treatment as every other Hibernate parent-reference field in this crate (see
//! `entity` module docs).

use date_range_rs::DateTimeRange;
use joda_rs::LocalDateTime;

/// A pre-scheduled employee/shift assignment, entered directly rather than generated by the
/// pipeline. `PreSchedule`.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct PreSchedule {
    id: i32,
    employee_id: i32,
    job_id: i32,
    start_date_time: LocalDateTime,
    end_date_time: LocalDateTime,
    shift_category_id: Option<i32>,
    assignment_id: Option<i32>,
}

impl PreSchedule {
    pub fn new(
        id: i32,
        employee_id: i32,
        job_id: i32,
        start_date_time: LocalDateTime,
        end_date_time: LocalDateTime,
    ) -> Self {
        Self {
            id,
            employee_id,
            job_id,
            start_date_time,
            end_date_time,
            shift_category_id: None,
            assignment_id: None,
        }
    }

    /// `setShiftCategory(ShiftCategory)`.
    #[must_use]
    pub fn with_shift_category_id(mut self, shift_category_id: i32) -> Self {
        self.shift_category_id = Some(shift_category_id);
        self
    }

    /// `setAssignment(Assignment)`.
    #[must_use]
    pub fn with_assignment_id(mut self, assignment_id: i32) -> Self {
        self.assignment_id = Some(assignment_id);
        self
    }

    /// `getID()`.
    pub fn id(&self) -> i32 {
        self.id
    }

    /// `getEmployee().getID()`.
    pub fn employee_id(&self) -> i32 {
        self.employee_id
    }

    /// `getJob().getID()`.
    pub fn job_id(&self) -> i32 {
        self.job_id
    }

    /// `getStartDateTime()`.
    pub fn start_date_time(&self) -> LocalDateTime {
        self.start_date_time
    }

    /// `getShiftCategory().getID()` — `null` when unset.
    pub fn shift_category_id(&self) -> Option<i32> {
        self.shift_category_id
    }

    /// `getAssignment().getID()` — `null` when unset.
    pub fn assignment_id(&self) -> Option<i32> {
        self.assignment_id
    }

    /// `toDateTimeRange()`.
    pub fn to_date_time_range(&self) -> DateTimeRange {
        DateTimeRange::of(self.start_date_time, self.end_date_time)
    }
}
