//! Port of `com.unifocus.watson.common.enums.PunchSource`.
//!
//! Where a punch came from. Punch-rounding rules gate on this: a rule set can
//! round clock punches but leave manually entered ones alone, or the reverse.
//! Like `PunchType`, the codes are shared with the UFTC time clock.

use crate::coded_enum;

coded_enum! {
    /// How a punch was recorded. `PunchSource`.
    PunchSource {
        /// Generated by the system rather than entered by anyone.
        Auto => "A",
        /// Entered at a time clock.
        Clock => "C",
        /// Keyed in by hand.
        Manual => "M",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_code_round_trips() {
        for value in PunchSource::VALUES {
            assert_eq!(PunchSource::from_code(value.code()), Some(*value));
        }
    }

    #[test]
    fn the_codes_are_single_letters() {
        assert_eq!(PunchSource::Auto.code(), "A");
        assert_eq!(PunchSource::Clock.code(), "C");
        assert_eq!(PunchSource::Manual.code(), "M");
    }
}
